### PR TITLE
Check if tray is running before trying to kill it during cleanup

### LINKED ISSUE #2433: [BUG] cleanup error when tray process does not exist
### General information

On windows platform from time to time the tray shows unhandled errors, the only options from there is quit the tray. After quit the tray if the user wants to cleanup crc the log shows an error as it is expected to clean the tray process which does not exist anymore  
  
## CRC version
```bash
CodeReady Containers version: 1.28.0+08de64bd
OpenShift version: 4.7.13 (not embedded in executable)
```
 
### Steps to reproduce

  1. Install crc from msi
  2. Exit tray 
  3. `crc cleanup`

### Expected

cleanup execution finish successfully

### Actual

cleanup execution ends up showing an unhandle error. status code 1

### Logs

```bash
INFO Stopping tray if running
INFO Uninstalling daemon if installed
INFO Removing hosts file records added by CRC
INFO Uninstalling admin-helper daemon
INFO Will run as admin: uninstall admin-helper daemon
INFO Removing the crc VM if exists
INFO Removing dns server from interface
INFO Will run as admin: Remove dns entry for default switch
INFO Removing pull secret from the keyring
INFO Removing older logs
INFO Removing CRC Machine Instance directory
Failed to kill tray process: exit status 1```

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #2433

- Check if the tray is running before attempting to kill the tray process, this prevents showing an error at the end of cleanup
- Removes the `crc-users` group during cleanup

### CODE REVIEW

File: pkg/crc/preflight/preflight_checks_tray_windows.go [hunk 1]
```diff
@@ -31,7 +31,9 @@ func stopTray() error {
 	 * this tries to stop the old tray process, can be removed after a  few releases
 	 */
 	_, _, _ = powershell.Execute(`Stop-Process -Name tray-windows`)
-
+	if err := checkIfTrayRunning(); err != nil {
```
Comment (cfergeau) [inline pkg/crc/preflight/preflight_checks_tray_windows.go:34]: Might be nice to extend the error reporting to be able to differentiate between "tray is not running" and "some other failure occurred" (no need for changes in this PR)

**Review by cfergeau — APPROVED** [review]
