### PR TITLE
Embed the binaries we need in 'crc' to support offline installs

### LINKED ISSUE #509: Support 'offline' installs
At the moment, at `crc setup` time, we download `oc`, and the crc machine driver that we need. This will fail if run on a machine with limited network connectivity, so it would be better if all the needed binaries were included in the tarball or embedded.

### PR DESCRIPTION
**Pull request by cfergeau**
At the moment, crc needs external network access in order to download
and install oc and its machine drivers. This is not going to be possible
in some environment where external access is disabled.
This patch series adds a new helper used at build time which will download
the misc required binaries and embed them in the 'crc' binary. Then these
binaries will be used instead of downloading them.
This fixes #509

### CODE REVIEW

File: pkg/crc/constants/constants.go [hunk 1]
```diff
@@ -25,8 +26,27 @@ const (
 	GlobalStateFile      = "globalstate.json"
 	CrcLandingPageURL    = "https://cloud.redhat.com/openshift/install/crc/installer-provisioned" // #nosec G101
 	PullSecretFile       = "pullsecret.json"
+
+	DefaultOcURLDarwin  = "https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/macosx/oc.tar.gz"
+	DefaultOcURLLinux   = "https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz"
+	DefaultOcURLWindows = "https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/windows/oc.zip"
```
Comment (praveenkumar) [inline pkg/crc/constants/constants.go]: Why we need those `DefaultOcURL<OS>` variables when we are getting it from `GetOcUrl` side?

Comment (cfergeau) [reply pkg/crc/constants/constants.go]: I forgot to remove these :) Thanks!

**Comment by praveenkumar** [comment]
retest this please.

File: pkg/crc/machine/hyperkit/constants.go [hunk 2]
```diff
@@ -1,3 +1,5 @@
+//+build darwin build
```
Comment (cfergeau) [inline pkg/crc/machine/hyperkit/constants.go]: It seems using a `crc` build tag when building the `crc` binary (ie making this line `//+build darwin !crc`) would mean less changes to `Makefile`, I can post this alternate version.

File: Makefile [hunk 3]
```diff
@@ -199,7 +199,7 @@ check_bundledir:
 	@$(call check_defined, BUNDLE_DIR, "Embedding bundle requires BUNDLE_DIR set to a directory containing CRC bundles for all hypervisors")
 
 embed_bundle: LDFLAGS += $(BUNDLE_EMBEDDED)
-embed_bundle: clean cross $(GOPATH)/bin/binappend-cli check_bundledir $(HYPERKIT_BUNDLENAME) $(HYPERV_BUNDLENAME) $(LIBVIRT_BUNDLENAME)
-	$(GOPATH)/bin/binappend-cli write $(BUILD_DIR)/linux-amd64/crc $(LIBVIRT_BUNDLENAME)
-	$(GOPATH)/bin/binappend-cli write $(BUILD_DIR)/macos-amd64/crc $(HYPERKIT_BUNDLENAME)
-	$(GOPATH)/bin/binappend-cli write $(BUILD_DIR)/windows-amd64/crc.exe $(HYPERV_BUNDLENAME)
+embed_bundle: clean cross build-aux/crc-embedder check_bundledir $(HYPERKIT_BUNDLENAME) $(HYPERV_BUNDLENAME) $(LIBVIRT_BUNDLENAME)
+	build-aux/crc-embedder embed --goos=darwin --bundle-dir=$(BUNDLE_DIR) $(BUILD_DIR)/macos-amd64/crc
```
Comment (gbraad) [inline Makefile]: wondering why this is `build-aux`. is this intended as a place for more build related tooling?

Comment (cfergeau) [reply Makefile]: If we need more build tools in the future, yes they could go there. But this is just a name I picked from my autotools day, I don't mind changing it to something different.

Comment (gbraad) [reply Makefile]: just wondering... not a problem. it almost suggest you have more tools on mind,... if so, what are those?

Comment (cfergeau) [reply Makefile]: nope, definitely no additional tool in mind :) Not even sure it would be convenient to build 2 binaries from the same dir with go.

Comment (gbraad) [reply Makefile]: actually, the patter for that is `cmd/build-aux`, just like `cmd/crc`. the second `cmd` in `cmd/crc/cmd` is actually for cobra/viper.

**Comment by praveenkumar** [comment]
@cfergeau this now need a rebase.

**Comment by praveenkumar** [comment]
retest this please,

File: build-aux/cmd/list.go [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+		runList(args)
+	},
+}
+
+func runList(args []string) {
+	if len(args) != 1 {
+		logging.Fatalf("list takes exactly one argument")
+	}
+	binaryPath := args[0]
+	output.Outln("List")
```
Comment (praveenkumar) [inline build-aux/cmd/list.go]: This is not required otherwise it will show as below.
```
List
Data files embedded in out/macos-amd64/crc:
	 crc-driver-hyperkit
	 crc_hyperkit_4.2.12.crcbundle
	 hyperkit
	 oc.tar.gz
```

File: Makefile [hunk 5]
```diff
@@ -91,12 +87,15 @@ $(BUILD_DIR)/linux-amd64/crc: $(SOURCES)
 $(BUILD_DIR)/windows-amd64/crc.exe: $(SOURCES)
 	GOARCH=amd64 GOOS=windows go build -ldflags="$(LDFLAGS)" -o $(BUILD_DIR)/windows-amd64/crc.exe ./cmd/crc
 
+build-aux/crc-embedder: $(SOURCES) build-aux/crc-embedder.go
```
Comment (praveenkumar) [inline Makefile]: why we require `build-aux/crc-embedder.go` for this target? I tested it on mac without adding it and it does work without any issue.

File: Makefile [hunk 6]
```diff
@@ -199,7 +199,7 @@ check_bundledir:
...
 
 embed_bundle: LDFLAGS += $(BUNDLE_EMBEDDED)
-embed_bundle: clean cross $(GOPATH)/bin/binappend-cli check_bundledir $(HYPERKIT_BUNDLENAME) $(HYPERV_BUNDLENAME) $(LIBVIRT_BUNDLENAME)
-	$(GOPATH)/bin/binappend-cli write $(BUILD_DIR)/linux-amd64/crc $(LIBVIRT_BUNDLENAME)
-	$(GOPATH)/bin/binappend-cli write $(BUILD_DIR)/macos-amd64/crc $(HYPERKIT_BUNDLENAME)
-	$(GOPATH)/bin/binappend-cli write $(BUILD_DIR)/windows-amd64/crc.exe $(HYPERV_BUNDLENAME)
+embed_bundle: clean cross build-aux/crc-embedder check_bundledir $(HYPERKIT_BUNDLENAME) $(HYPERV_BUNDLENAME) $(LIBVIRT_BUNDLENAME)
+	build-aux/crc-embedder embed --goos=darwin --bundle-dir=$(BUNDLE_DIR) $(BUILD_DIR)/macos-amd64/crc
+	build-aux/crc-embedder embed --goos=linux --bundle-dir=$(BUNDLE_DIR) $(BUILD_DIR)/linux-amd64/crc
+	build-aux/crc-embedder embed --goos=windows --bundle-dir=$(BUNDLE_DIR) $(BUILD_DIR)/windows-amd64/crc.exe
```
Comment (praveenkumar) [inline Makefile]: We should use `--log-level debug` here since this is the step which is going to run on the CI so better to have debug logs if possible.

File: Makefile [hunk 7]
```diff
@@ -91,12 +87,15 @@ $(BUILD_DIR)/linux-amd64/crc: $(SOURCES)
 $(BUILD_DIR)/windows-amd64/crc.exe: $(SOURCES)
 	GOARCH=amd64 GOOS=windows go build -ldflags="$(LDFLAGS)" -o $(BUILD_DIR)/windows-amd64/crc.exe ./cmd/crc
 
+build-aux/crc-embedder: $(SOURCES) build-aux/crc-embedder.go
+	go build --tags="build" -ldflags="$(LDFLAGS)" -o build-aux/crc-embedder ./build-aux
```
Comment (praveenkumar) [inline Makefile]: Shouldn't we use `BUILD_DIR` for all the binary generation part? Following patch have all the diff which I think should be considered.

```patch
-build-aux/crc-embedder: $(SOURCES) build-aux/crc-embedder.go
-       go build --tags="build" -ldflags="$(LDFLAGS)" -o build-aux/crc-embedder ./build-aux
+build-aux/crc-embedder: $(SOURCES)
+       go build --tags="build" -ldflags="$(LDFLAGS)" -o $(BUILD_DIR)/crc-embedder ./build-aux
 
 .PHONY: cross ## Cross compiles all binaries
 cross: $(BUILD_DIR)/macos-amd64/crc $(BUILD_DIR)/linux-amd64/crc $(BUILD_DIR)/windows-amd64/crc.exe
@@ -200,6 +200,6 @@ check_bundledir:
 
 embed_bundle: LDFLAGS += $(BUNDLE_EMBEDDED)
 embed_bundle: clean cross build-aux/crc-embedder check_bundledir $(HYPERKIT_BUNDLENAME) $(HYPERV_BUNDLENAME) $(LIBVIRT_BUNDLENAME)
-       build-aux/crc-embedder embed --goos=darwin --bundle-dir=$(BUNDLE_DIR) $(BUILD_DIR)/macos-amd64/crc
-       build-aux/crc-embedder embed --goos=linux --bundle-dir=$(BUNDLE_DIR) $(BUILD_DIR)/linux-amd64/crc
-       build-aux/crc-embedder embed --goos=windows --bundle-dir=$(BUNDLE_DIR) $(BUILD_DIR)/windows-amd64/crc.exe
+       $(BUILD_DIR)/crc-embedder embed --goos=darwin --bundle-dir=$(BUNDLE_DIR) $(BUILD_DIR)/macos-amd64/crc --log-level debug
+       $(BUILD_DIR)/crc-embedder embed --goos=linux --bundle-dir=$(BUNDLE_DIR) $(BUILD_DIR)/linux-amd64/crc --log-level debug
+       $(BUILD_DIR)/crc-embedder embed --goos=windows --bundle-dir=$(BUNDLE_DIR) $(BUILD_DIR)/windows-amd64/crc.exe --log-level debug
```

File: Makefile (hunk 5 above)
Comment (cfergeau) [reply Makefile]: Ah right it should be part of $(SOURCES). I'll try to drop it.

File: Makefile (hunk 7 above)
Comment (cfergeau) [reply Makefile]: dunno what are the conventions for go + Makefile :) if you prefer things this way, no objections from me, I'll change.

File: Makefile [hunk 8]
```diff
@@ -31,11 +31,12 @@ DOCS_BUILD_TARGET ?= /docs/source/getting-started/master.adoc
 
 GOOS ?= $(shell go env GOOS)
 GOARCH ?= $(shell go env GOARCH)
+HOST_BUILD_DIR=$(BUILD_DIR)/$(GOOS)-$(GOARCH)
```
Comment (praveenkumar) [inline Makefile]: @cfergeau Any specific reason not directly using the `$(BUILD_DIR)` one instead creating a new directory?

Comment (cfergeau) [reply Makefile]: The `out` directory contains `out/macos-amd64/crc`, `out/linux-amd64/crc` and `out/win-amd64/crc.exe`, it felt odd to add a `out/crc-embedder` binary rather than putting it in the correct `out/$os-$arch/` directory.

Comment (praveenkumar) [reply Makefile]: Ack 👍

Comment (cfergeau) [reply Makefile]: actually, I suspect on macos, `$(GOOS)-$(GOARCH)` is going to be `darwin-amd64`, not `macos-amd64`, so an additional commit may be needed.

Comment (cfergeau) [reply Makefile]: Confirmed, but this does not cause a build failure, it just created `out/darwin-amd64/crc-embedder` in addition to `out/macos-amd64/crc`. I'll keep it that way for now.
