### PR TITLE
Preflight checks improvements

### LINKED ISSUE #990: [BUG] Start fails after cheking libvirtd
### General information

  * OS: Linux / macOS / Windows
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it? Yes

## CRC version
```bash
# crc version    
crc version: 1.5.0+e1c8fb8
OpenShift version: 4.2.14 (embedded in binary)

```
  
## CRC status
```bash
# crc status                 
CRC VM:          Stopped
OpenShift:       Stopped
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     11.98GB
Cache Directory: /home/b1zzu/.crc/cache
```

## CRC config

Doesn't print anything

```bash
# crc config view
```

## Host Operating System

```bash
NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

```

### Steps to reproduce

  1.  `crc setup`
  2.  `crc start` On the first time it works
  3.  `crc stop`
  4.  `crc start`

### Expected

To start OpenShift

### Actual

It doesn't start

### Logs

```
# crc start --log-level debug
DEBU No new version available. The latest version is 1.5.0 
INFO Checking if oc binary is cached              
DEBU oc binary already cached                     
INFO Checking if running as non-root              
INFO Checking if Virtualization is enabled        
DEBU Checking if the vmx/svm flags are present in /proc/cpuinfo 
DEBU CPU virtualization flags are good            
INFO Checking if KVM is enabled                   
DEBU Checking if /dev/kvm exists                  
DEBU /dev/kvm was found                           
INFO Checking if libvirt is installed             
DEBU Checking if 'virsh' is available             
DEBU 'virsh' was found in /usr/bin/virsh          
INFO Checking if user is part of libvirt group    
DEBU Checking if current user is part of the libvirt group 
DEBU Current user is already in the libvirt group 
INFO Checking if libvirt is enabled               
DEBU Checking if libvirtd.service is enabled      
DEBU libvirtd.service is already enabled          
INFO Checking if libvirt daemon is running        
DEBU Checking if libvirtd.service is running      
DEBU exit status 3 :                              
FATA exit status 3 :
```

I would like to add more but this is really everything I have

### PR DESCRIPTION
**Pull request by cfergeau**
This pull-request can be split in 2 different parts
- first one improves the preflight checks related to libvirt crc network
- second part improves the error messages which are shown to the user when preflight failures happen

It fixes #990 and #995.

### CODE REVIEW

File: pkg/crc/preflight/preflight_checks_linux.go [hunk 1]
```diff
@@ -48,34 +47,35 @@ func checkVirtualizationEnabled() error {
...
-		return errors.New("Could not find cpu flags from /proc/cpuinfo")
+		return fmt.Errorf("Could not find cpu flags from /proc/cpuinfo")
 	}
 
 	re = regexp.MustCompile(`(vmx|svm)`)
 
 	cputype := re.FindString(flags)
 	if cputype == "" {
-		return errors.New("Virtualization is not available for you CPU")
+		return fmt.Errorf("Virtualization is not available for you CPU")
```
Comment (robin-owen) [inline pkg/crc/preflight/preflight_checks_linux.go]: Typo: "your CPU"

**Comment by praveenkumar** [comment]
retest this please.

File: pkg/os/exec.go [hunk 2]
```diff
@@ -5,33 +5,44 @@ import (
...
-	cmd := exec.Command(command, args...) // #nosec G204
-	cmd.Env = ReplaceEnv(os.Environ(), "LC_ALL", "C")
-	cmd.Env = ReplaceEnv(cmd.Env, "LANG", "C")
-	stdOut := new(bytes.Buffer)
-	stdErr := new(bytes.Buffer)
-	cmd.Stdout = stdOut
-	cmd.Stderr = stdErr
-	err := cmd.Run()
-	return stdOut.String(), stdErr.String(), err
+	return run(command, args, map[string]string{"LC_ALL": "C", "LANG": "C"})
```
Comment (praveenkumar) [inline pkg/os/exec.go]: @cfergeau in the `run` function you already using the `LC_ALL` and `LANG` env value so why we are passing this here again?

```golang
func run(command string, args []string, env map[string]string) (string, string, error) {
	cmd := exec.Command(command, args...) // #nosec G204
	cmd.Env = ReplaceEnv(os.Environ(), "LC_ALL", "C")
	cmd.Env = ReplaceEnv(cmd.Env, "LANG", "C")
...
```

Comment (cfergeau) [reply pkg/os/exec.go]: I forgot to remove these lines from `run`, thanks for spotting this!
