### PR TITLE
#1948 don't use viper to write the config file

### LINKED ISSUE #1948: [BUG] Unwanted config key in crc.json after crc setup
### General information

  * OS: All

### Steps to reproduce

With an empty ~/.crc directory
  1. crc setup

### Expected

```
$ cat ~/.crc/crc.json 
{
  "consent-telemetry": "no",
}          
```

### Actual

```
$ cat ~/.crc/crc.json 
{
  "consent-telemetry": "no",
  "enable-experimental-features": false,
  "help": false,
  "log-level": "info",
  "output": ""
}       
```

### PR DESCRIPTION
**Pull request by guillaumerose**
Viper is not made for writing config file. When using flags, it adds
them in the config file even if they are not config key we defined.
    
This change uses traditional method to edit json and then, asks viper to
reload the configuration.

Fixes #1948

### CODE REVIEW

**Comment by cfergeau** [comment]
> Viper is not made for writing config file

Given that it has API for that, plus documentation around it https://github.com/spf13/viper/#writing-config-files , I beg to disagree with that statement. After reading the next sentence, I can agree with "viper.WriteConfig is not the right API for what we are trying to do" though :)

**Comment by guillaumerose** [comment]
I reworded the commit log :)

File: pkg/crc/config/viper_config_test.go [hunk 1]
```diff
@@ -181,13 +181,13 @@ func TestViperConfigBindFlagSet(t *testing.T) {
 	assert.NoError(t, err)
 
 	assert.Equal(t, SettingValue{
-		Value:     6,
+		Value:     5, // flag has the priority
```
Comment (praveenkumar) [inline pkg/crc/config/viper_config_test.go:184]: @guillaumerose does that mean we were ignoring the flag priority over what present in config?

Comment (guillaumerose) [reply pkg/crc/config/viper_config_test.go:184]: no this is a weird case where someone would launch `crc config set cpus 8 --cpus 10`.  This is purely theoretical. Set a key and at the same time set it with flag.

Comment (praveenkumar) [reply pkg/crc/config/viper_config_test.go:184]: @guillaumerose for me, it leads to following error which make sense.
 
```
$ ./crc config set cpus 6 --cpus 10
unknown flag: --cpus
```

But when I am looking the test case I think we are adding the flags and only for test case it might be the case. Can't we just remove it? It will be confusing over time.

Comment (guillaumerose) [reply pkg/crc/config/viper_config_test.go]: I removed the assertion :+1:

**Comment by cfergeau** [comment]
Fwiw, I think `When using flags, it adds them in the config file even if they are not config key we defined.` used to work fine (ie crc's code was being careful so that these flags don't end up in the config file - assuming by 'flags' you mean `--memory` and such)

File: pkg/crc/config/viper_config.go [hunk 2]
```diff
@@ -45,21 +44,43 @@ func (c *ViperStorage) Get(key string) interface{} {
...
+	}
+	cfg[key] = value
+	bin, err := json.MarshalIndent(cfg, "", "  ")
+	if err != nil {
+		return err
+	}
+	if err := atomicWrite(bin, c.configFile); err != nil {
+		return err
+	}
+	return c.viper.ReadInConfig()
```
Comment (cfergeau) [inline pkg/crc/config/viper_config.go:63]: Adding more and more IO for each `Set`/`Unset`/... does not feel like they way to go to be honest :-/

File: pkg/crc/config/viper_config_test.go [hunk 3]
```diff
@@ -183,6 +184,10 @@ func TestViperConfigBindFlagSet(t *testing.T) {
 		Value:     6,
 		IsDefault: false,
 	}, config.Get(CPUs))
+
+	bin, err := ioutil.ReadFile(configFile)
+	assert.NoError(t, err)
+	assert.JSONEq(t, `{"cpus":6,"extra":"","nameservers":""}`, string(bin))
```
Comment (cfergeau) [inline pkg/crc/config/viper_config_test.go]: Not clear if this is a 'theoritical' issue though, or if this can happen while using crc.

**Comment by guillaumerose** [comment]
Set/Unset worked fine as long as you don't use them when you BindFlags. 
If you do crc start --memory 10000 and also do Set("cpus", 10) for an other reason, you end up with both memory and cpus changed in the config file.

File: pkg/crc/config/viper_config.go (hunk 2 above)
Comment (guillaumerose) [reply pkg/crc/config/viper_config.go:63]: Yes.. I added as many tests as possible so that we can refactor that someday if we have better ideas.

Comment (cfergeau) [reply pkg/crc/config/viper_config.go:63]: Oh I have better ideas, but this requires significant work, so not quite realistic now ;) (real IPC signaling rather than using files for config change notifications, better eventloop in crc so that we can delay writing of the config file, ...)
