### PR TITLE
Issue #110 Prevent segfault because of calling err.Error() on empty err

### LINKED ISSUE #110: Pre-flight check fails when checking for group membership of the user
Tried `crc start` without the bundle downloaded yet and got a panic error:

```
jeffmaury@localhost crc-0.85.0-linux-amd64]$ ./crc start
crc - Local OpenShift 4.x cluster
INFO  Checking if Virtualization is enabled       
INFO  Checking if KVM is enabled                  
INFO  Checking if Libvirt is installed            
INFO  Checking if user is part of libvirt group   
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x884e68]

goroutine 1 [running]:
github.com/code-ready/crc/pkg/crc/preflight.preflightCheckSucceedsOrFails(0x9a6300, 0x9bb8f8, 0x9ab201, 0x29, 0x0)
	/home/prkumar/work/github/crc/pkg/crc/preflight/preflight_common.go:26 +0x188
github.com/code-ready/crc/pkg/crc/preflight.StartPreflightChecks()
	/home/prkumar/work/github/crc/pkg/crc/preflight/preflight_linux.go:25 +0x201
github.com/code-ready/crc/cmd/crc/cmd.runStart(0xddadb8, 0x0, 0x0)
	/home/prkumar/work/github/crc/cmd/crc/cmd/start.go:41 +0xce
github.com/code-ready/crc/cmd/crc/cmd.glob..func6(0xdb3b00, 0xddadb8, 0x0, 0x0)
	/home/prkumar/work/github/crc/cmd/crc/cmd/start.go:25 +0x3f
github.com/spf13/cobra.(*Command).execute(0xdb3b00, 0xddadb8, 0x0, 0x0, 0xdb3b00, 0xddadb8)
	/home/prkumar/work/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xdb3640, 0xdb3fc0, 0xc00017df68, 0xc00017df88)
	/home/prkumar/work/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xdb3640, 0x1, 0xdb3fc0)
	/home/prkumar/work/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
github.com/code-ready/crc/cmd/crc/cmd.Execute()
	/home/prkumar/work/github/crc/cmd/crc/cmd/root.go:59 +0x2d
main.main()
	/home/prkumar/work/github/crc/cmd/crc/main.go:8 +0x20
[jeffmaury@localhost crc-0.85.0-linux-amd64]$ 

```

### LINKED ISSUE #159: Handle the errors effectively to prevent segfault/panic
Looks like some of the errors are either we ignored or not handled correctly and that need to address properly.

- If a member is not part of `libvirt` group and user just use `crc start` before `crc setup` it will give panic.

- If user use `crc start` on already running instance that also give the panic.

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #110
Fixes #159

### CODE REVIEW

File: pkg/crc/machine/machine.go [hunk 1]
```diff
@@ -93,15 +93,19 @@ func Start(startConfig StartConfig) (StartResult, error) {
...
 		result.Status = vmState.String()
 	} else {
-		logging.InfoF(" Starting stopped VM ...")
 		host, err := libMachineAPIClient.Load(machineConfig.Name)
 		s, err := host.Driver.GetState()
 		if err != nil {
 			logging.ErrorF("Error getting the state for host: %s", err)
 			result.Error = err.Error()
 		}
+		if s == state.Running {
```
Comment (anjannath) [inline pkg/crc/machine/machine.go]: If we have this check early on in the start command, then we can prevent performing the preflight checks. I am for putting it there.. but since all the machine stuff is here added it here, would like to know what @gbraad @praveenkumar thinks!

File: pkg/crc/preflight/preflight_common.go [hunk 2]
```diff
@@ -23,7 +23,7 @@ func preflightCheckSucceedsOrFails(configuredToSkip bool, check PreflightCheckFi
 		return
 	}
 
-	log.Fatal(err.Error())
+	log.FatalF(" Above Check Failed: %+v", err)
```
Comment (praveenkumar) [inline pkg/crc/preflight/preflight_common.go]: :+1:

File: pkg/crc/machine/machine.go (hunk 1 above)
Comment (praveenkumar) [reply pkg/crc/machine/machine.go]: I don't know, this is like early feedback that machine already running ?

Comment (anjannath) [reply pkg/crc/machine/machine.go]: Yes, i am for doing this check in the start command.. even before calling `machine.Start()` and starting the preflight checks..

Comment (gbraad) [reply pkg/crc/machine/machine.go]: This is a different issue... valuable, but no need to address here

File: pkg/crc/machine/machine.go [hunk 3]
```diff
@@ -93,15 +93,19 @@ func Start(startConfig StartConfig) (StartResult, error) {
...
+			result.Status = s.String()
+			return *result, err
```
Comment (gbraad) [inline pkg/crc/machine/machine.go]: what valuse has `err` here?

This is to shortcircuit the `start` when the VM is already in a running state

Comment (anjannath) [reply pkg/crc/machine/machine.go]: Any error that might have occurred during getting the state of the VM :P 
Yup does not make sense.. if we already get into the if block.. will just return `nil` instead!

Comment (gbraad) [reply pkg/crc/machine/machine.go]: In that case line 102 should be a return of the error... right?
as originally it just continues and would check the running state and try again, but if the previous call failed, that would fail also.

same actually here. it misses the return of the error

Comment (anjannath) [reply pkg/crc/machine/machine.go]: @gbraad Updated return value to `nil`.

File: pkg/crc/preflight/preflight_common.go (hunk 2 above)
Comment (praveenkumar) [reply pkg/crc/preflight/preflight_common.go]: So our error should be correctly returned I think current solution doesn't going well in long term so better fix the function which return that error as `nil` even result is false.

**Comment by praveenkumar** [comment]
here https://github.com/code-ready/crc/blob/master/pkg/crc/preflight/preflight_checks_linux.go#L161 this should have been.

```
return false, errors.NewF("%s not part of libvirtd group", currentUser.Username)
```

File: pkg/crc/preflight/preflight_checks_linux.go [hunk 4]
```diff
@@ -172,10 +172,10 @@ func checkUserPartOfLibvirtGroup() (bool, error) {
 		return false, fmt.Errorf("%+v : %s", err, stdErr)
 	}
 	if strings.Contains(stdOut, "libvirt") {
-	        logging.Debug("Current user is already in the libvirt group")
+		logging.Debug("Current user is already in the libvirt group")
 		return true, nil
 	}
-	return false, err
+	return false, errors.NewF("%s not part of libvirtd group", currentUser.Username)
```
Comment (praveenkumar) [inline pkg/crc/preflight/preflight_checks_linux.go]: 👍
