### PR TITLE
Don't crash when machine.createHost() fails

### LINKED ISSUE #219: 'no space left on device' exception should be handled more graceful
while starting crc I received:
```
ERRO Error occured: Error creating the VM. [Error creating machine: Error in driver during machine creation: write /home/goern/.crc/machines/crc/crc.tmp151717532: no space left on device] 
ERRO Error creating host: Error creating the VM. Error creating machine: Error in driver during machine creation: write /home/goern/.crc/machines/crc/crc.tmp151717532: no space left on device 
Making call to close driver server
(crc) Calling .Close
Successfully made call to close driver server
Making call to close connection to plugin binary
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa97d5e]

goroutine 1 [running]:
github.com/code-ready/crc/pkg/crc/machine.Start(0xd1a872, 0x3, 0x7ffe7bffbe6d, 0x33, 0xd1df86, 0x7, 0x2000, 0x4, 0x1, 0x0, ...)
	/home/goern/Source/github.com/code-ready/crc/pkg/crc/machine/machine.go:98 +0x1c5e
github.com/code-ready/crc/cmd/crc/cmd.runStart(0xc000228a00, 0x0, 0x4)
	/home/goern/Source/github.com/code-ready/crc/cmd/crc/cmd/start.go:55 +0x258
github.com/code-ready/crc/cmd/crc/cmd.glob..func6(0x144d480, 0xc000228a00, 0x0, 0x4)
	/home/goern/Source/github.com/code-ready/crc/cmd/crc/cmd/start.go:31 +0x3f
github.com/spf13/cobra.(*Command).execute(0x144d480, 0xc000228980, 0x4, 0x4, 0x144d480, 0xc000228980)
	/home/goern/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x144de00, 0x4074af, 0xc0000ae058, 0x0)
	/home/goern/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/home/goern/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/code-ready/crc/cmd/crc/cmd.Execute()
	/home/goern/Source/github.com/code-ready/crc/cmd/crc/cmd/root.go:64 +0x2e
main.main()
	/home/goern/Source/github.com/code-ready/crc/cmd/crc/main.go:10 +0x25
```

This should be handled in a more user friendly way, dumping the stack track is not that helpful to a user.

### PR DESCRIPTION
**Pull request by cfergeau**
There are plenty of reasons why this function may fail, and when this
happens, we get a nil 'host'. As we try to use 'host' just after
calling machine.createHost(), we need to return otherwise we'll get a
crash.

This should resolve #219
https://github.com/code-ready/crc/issues/219

INFO Creating VM ...
ERRO Error occured: Error creating the VM. [Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"]
ERRO Error creating host: Error creating the VM. Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14639a6]

goroutine 1 [running]:
github.com/code-ready/crc/pkg/crc/machine.Start(0x164d6b0, 0x3, 0xc0000d8720, 0x1d, 0x7ffeefbffc19, 0xa, 0x2000, 0x4, 0x0, 0x0, ...)
        /Users/teuf/go/src/github.com/code-ready/crc/pkg/crc/machine/machine.go:99 +0x20a6
github.com/code-ready/crc/cmd/crc/cmd.runStart(0xc0001a6000, 0x0, 0x2)
        /Users/teuf/go/src/github.com/code-ready/crc/cmd/crc/cmd/start.go:55 +0x258
github.com/code-ready/crc/cmd/crc/cmd.glob..func6(0x1b5d520, 0xc0001a6000, 0x0, 0x2)
        /Users/teuf/go/src/github.com/code-ready/crc/cmd/crc/cmd/start.go:31 +0x3f
github.com/code-ready/crc/vendor/github.com/spf13/cobra.(*Command).execute(0x1b5d520, 0xc0000bffe0, 0x2, 0x2, 0x1b5d520, 0xc0000bffe0)
        /Users/teuf/go/src/github.com/code-ready/crc/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/code-ready/crc/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1b5dea0, 0x100775f, 0xc000092058, 0x0)
        /Users/teuf/go/src/github.com/code-ready/crc/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/code-ready/crc/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/teuf/go/src/github.com/code-ready/crc/vendor/github.com/spf13/cobra/command.go:800
github.com/code-ready/crc/cmd/crc/cmd.Execute()
        /Users/teuf/go/src/github.com/code-ready/crc/cmd/crc/cmd/root.go:63 +0x2e
main.main()
        /Users/teuf/go/src/github.com/code-ready/crc/cmd/crc/main.go:10 +0x25

### CODE REVIEW

**Comment by cfergeau** [comment]
There are more places in `machine.Start` where errors are checked but the function does not return. I did not look closely at them, so I don't know whether this is a problem or not.
```
diff --git a/pkg/crc/machine/machine.go b/pkg/crc/machine/machine.go
index 7b36c8d..915e29f 100644
--- a/pkg/crc/machine/machine.go
+++ b/pkg/crc/machine/machine.go
@@ -101,6 +101,7 @@ func Start(startConfig StartConfig) (StartResult, error) {
 		if err != nil {
 			logging.ErrorF("Error getting the state for host: %v", err)
 			result.Error = err.Error()
+			return *result, err
 		}
 
 		result.Status = vmState.String()
@@ -116,6 +117,7 @@ func Start(startConfig StartConfig) (StartResult, error) {
 		if err != nil {
 			logging.ErrorF("Error getting the state for host: %v", err)
 			result.Error = err.Error()
+			return *result, err
 		}
 		if s == state.Running {
 			result.Status = s.String()
@@ -127,10 +129,12 @@ func Start(startConfig StartConfig) (StartResult, error) {
 			if err := host.Driver.Start(); err != nil {
 				logging.ErrorF("Error starting stopped VM: %v", err)
 				result.Error = err.Error()
+				return *result, err
 			}
 			if err := libMachineAPIClient.Save(host); err != nil {
 				logging.ErrorF("Error saving state for VM: %v", err)
 				result.Error = err.Error()
+				return *result, err
 			}
 		}
 
@@ -138,6 +142,7 @@ func Start(startConfig StartConfig) (StartResult, error) {
 		if err != nil {
 			logging.ErrorF("Error getting the state: %v", err)
 			result.Error = err.Error()
+			return *result, err
 		}
 
 		result.Status = vmState.String()
```

File: pkg/crc/machine/machine.go [hunk 1]
```diff
@@ -94,6 +94,7 @@ func Start(startConfig StartConfig) (StartResult, error) {
 		if err != nil {
 			logging.ErrorF("Error creating host: %v", err)
 			result.Error = err.Error()
+			return *result, err
```
Comment (praveenkumar) [inline pkg/crc/machine/machine.go]: To me, if there is any error then return it as soon as we get and that's we were not doing it. this looks good approach.
