### PR TITLE
Fix grammatical error in error message

### LINKED ISSUE #1911: Grammatical issue: 'either' is a singular
https://github.com/code-ready/crc/blob/7b098c1bcaad0422dad36a390f8b335a9554548e/cmd/crc/cmd/start.go#L139

### PR DESCRIPTION
**Pull request by anjannath**
Since 'either' is singular it should be 'is' instead of 'are'

Fixes #1911

### CODE REVIEW

File: cmd/crc/cmd/start.go [hunk 1]
```diff
@@ -142,7 +142,7 @@ func (s *startResult) prettyPrintTo(writer io.Writer) error {
 		return s.Error
 	}
 	if s.ClusterConfig == nil {
-		return errors.New("either Error or ClusterConfig are needed")
+		return errors.New("either Error or ClusterConfig is needed")
```
Comment (praveenkumar) [inline cmd/crc/cmd/start.go:145]: 👍🏼

**Comment by gbraad** [comment]
Thanks. Was an old issue... but glad it got fixed ;-)
