### PR TITLE
e2e crc commands with envs repect platfom syntax

### LINKED ISSUE #2531: [e2e] Fix crc command execution with envs on windows
PR #2443 disabled update check from CI, the synxtax is valid for unix based platforms but it fails on windows.

### PR DESCRIPTION
**Pull request by adrianriobo**
Fixes #2531

### CODE REVIEW

**Comment by guillaumerose** [comment]
clicumber contains 7 files. Could we include them in this repo and directly modify the env ?
It will be easier to maintain also.

**Comment by adrianriobo** [comment]
About including the files in this repo seems fine to me. I will create a new PR for this. About  modify the env directly what do you mean?

**Comment by guillaumerose** [comment]
It is an open question, not a specific ask. I don't know what others think about that. Don't do it now ^^

File: test/e2e/crcsuite/crcsuite.go [hunk 1]
```diff
@@ -112,11 +112,11 @@ func FeatureContext(s *godog.Suite) {
 		}
 
 		// remove $HOME/.crc
-		err = util.RemoveCRCHome(CRCHome)
-		if err != nil {
-			fmt.Println(err)
-			os.Exit(1)
-		}
+		// err = util.RemoveCRCHome(CRCHome)
```
Comment (guillaumerose) [inline test/e2e/crcsuite/crcsuite.go:115]: Is it wanted ?

File: test/extended/crc/cmd/cmd.go [hunk 2]
```diff
@@ -15,6 +15,12 @@ const (
 	CRCExecutableNotInstalled = "notInstalled"
 )
 
+type Command struct {
```
Comment (guillaumerose) [inline test/extended/crc/cmd/cmd.go:18]: Good! In the future we could have a builder like `crc("setup").WithoutNTP().WithoutUpdateCheck()`.

File: test/extended/crc/cmd/cmd_unix.go [hunk 3]
```diff
@@ -0,0 +1,16 @@
+// +build !windows
+
+package cmd
+
+import "fmt"
+
+func (c Command) ToString() string {
```
Comment (guillaumerose) [inline test/extended/crc/cmd/cmd_unix.go:7]: I played a bit with the code. Here is what I got:

```

func (c Command) ToString() string {
	cmd := append(c.env(), "crc", c.Action)
	return strings.Join(cmd, " ")
}

func (c Command) env() []string {
	var env []string
	if c.DisableUpdateCheck {
		env = append(env, envVariable("CRC_DISABLE_UPDATE_CHECK", "true"))
	}
	if c.DisableNTP {
		env = append(env, envVariable("CRC_DEBUG_ENABLE_STOP_NTP", "true"))
	}
	return env
}

func envVariable(key, value string) string {
	if runtime.GOOS == "windows" {
		return fmt.Sprintf("$env:%s=%s;", key, value)
	}
	return fmt.Sprintf("%s=%s", key, value)
}

func TestCommand(t *testing.T) {
	assert.Equal(t, "crc setup", Command{
		Action: "setup",
	}.ToString())
	assert.Equal(t, "CRC_DEBUG_ENABLE_STOP_NTP=true crc start -b bundle", Command{
		Action:     "start -b bundle",
		DisableNTP: true,
	}.ToString())
	assert.Equal(t, "CRC_DISABLE_UPDATE_CHECK=true CRC_DEBUG_ENABLE_STOP_NTP=true crc start -b bundle", Command{
		Action:             "start -b bundle",
		DisableNTP:         true,
		DisableUpdateCheck: true,
	}.ToString())
}

```

It avoids to have a different file for Windows and share a bit more the code.

Comment (adrianriobo) [reply test/extended/crc/cmd/cmd_unix.go:7]: Cool seems fine, will add it.

File: test/e2e/crcsuite/crcsuite.go (hunk 1 above)
Comment (adrianriobo) [reply test/e2e/crcsuite/crcsuite.go:115]: no no I just realize, I was undoing :), but this need to be reviewed as now is failing on windows, because if crc-admin-helper process is running this remove fails (just commented to test on windows) but forget undo 

Thx though!

File: test/e2e/features/basic.feature [hunk 4]
```diff
@@ -4,12 +4,18 @@ Feature: Basic test
     User explores some of the top-level CRC commands while going
     through the lifecycle of CRC.
 
-    @darwin @linux @windows
+    @darwin @linux
     Scenario: CRC version
         When executing "CRC_DISABLE_UPDATE_CHECK=true crc version" succeeds
```
Comment (praveenkumar) [inline test/e2e/features/basic.feature:9]: @adrianriobo Shouldn't we just have a version function as part of `crcsuite.go` so we don't have to maintain the env setting in the feature file?

Comment (adrianriobo) [reply test/e2e/features/basic.feature:9]: Yeah definitely, I would prefer move towards that direction instead of executing...

Comment (adrianriobo) [reply test/e2e/features/basic.feature:9]: I will change this

File: test/e2e/crcsuite/crcsuite.go [hunk 5]
```diff
@@ -62,6 +62,10 @@ func FeatureContext(s *godog.Suite) {
 		CheckCRCStatus)
 	s.Step(`^(stdout|stderr) (?:should contain|contains) "(.*)" if bundle (is|is not) embedded$`,
 		CommandReturnShouldContainIfBundleEmbeddedOrNot)
+	s.Step(`^execute (.*) command$`,
```
Comment (praveenkumar) [inline test/e2e/crcsuite/crcsuite.go:65]: This looks very generic because it can capture `execute oc version command` which we don't want. Can't we do this something like `^execute crc (.*) coomand$` which will make sure it only capture crc specific commands?
