### PR TITLE
#2058 Create oc symlink at crc start time

### LINKED ISSUE #2058: [BUG] crc status is replacing oc symlink
### General information

  * OS: macOS

### Steps to reproduce

  1. crc status (with the tray)

### Expected

The status

### Actual

```
Error loading bundle metadata: symlink /Users/guillaumerose/.crc/cache/crc_hyperkit_4.7.0/oc /Users/guillaumerose/.crc/bin/oc/oc: file exists
```

### Description

Each time the code loads bundle details, it tries to re-create the symlink for oc. `crc status` destroys and recreates the symlink. It shouldn't. 

I believe this error happens on my mac because I have the tray polling the status every 5s.

### PR DESCRIPTION
**Pull request by guillaumerose**
Activate the bundle (eg install oc symlink) only on start action

Previously almost each commands recreated the symlink.
Fixes #2058

### CODE REVIEW

File: pkg/crc/machine/bundle/repository.go [hunk 1]
```diff
@@ -127,12 +127,17 @@ var defaultRepo = &Repository{
...
 
 func Get(bundleName string) (*CrcBundleInfo, error) {
-	return defaultRepo.Use(bundleName)
+	return defaultRepo.Get(bundleName)
+}
+
+func Use(bundleName string) error {
+	_, err := defaultRepo.Use(bundleName)
+	return err
 }
```
Comment (cfergeau) [inline pkg/crc/machine/bundle/repository.go:136]: Might be slightly odd that `Use` does not have the same return values as `(*Repo) Use`

File: pkg/crc/machine/start.go [hunk 2]
```diff
@@ -133,6 +133,10 @@ func (client *client) Start(ctx context.Context, startConfig StartConfig) (*Star
 			return nil, errors.Wrap(err, "Error getting bundle metadata")
 		}
 
+		if err := bundle.Use(filepath.Base(startConfig.BundlePath)); err != nil {
+			return nil, err
+		}
+
```
Comment (cfergeau) [inline pkg/crc/machine/start.go:139]: This could be moved to `getCrcBundleInfo()` which is only used here, or maybe `bundle.Use()` could be called a single time around the `// Post-VM start` comment? At this point we don't have ssh connectivity to the VM yet, so I don't think the code tries to use oc before that.

**Review by cfergeau — APPROVED** [review]
Looks good to me.

File: pkg/crc/machine/bundle/repository.go (hunk 1 above)
Comment (praveenkumar) [reply pkg/crc/machine/bundle/repository.go:136]: Agree, better to have to same return value as `(*Repo) Use` and we can ignore the no used value from the caller function.

File: pkg/crc/machine/start.go (hunk 2 above)
Comment (praveenkumar) [reply pkg/crc/machine/start.go:139]: `getCrcBundleInfo()` is only used at #131 and we should use `bundle.Use` there instead `bundle.Get` in the `getCrcBundleInfo()` and `bundle.Use` should also return the `bundleInfo` as mentioned https://github.com/code-ready/crc/pull/2062#discussion_r588125500 here.
