### PR TITLE
Issue #218 Approve node csr after cluster is up

### LINKED ISSUE #218: Alpha-2 (0.87.0): oc logs: remote error: tls: internal error
log can not be viewed...

How to reproduce:
```
$ oc new-project demo
$ oc process openshift//eap72-mongodb-s2i|oc apply -f -
$ oc get pod
NAME                       READY     STATUS      RESTARTS   AGE
eap-app-1-build            1/1       Running     0          3m34s
eap-app-mongodb-1-deploy   0/1       Completed   0          3m33s
eap-app-mongodb-1-r7827    1/1       Running     0          3m21s
$ oc logs eap-app-1-build
Error from server: Get https://crc-4gdnp-master-0:10250/containerLogs/demo/eap-app-1-build/sti-build: remote error: tls: internal error
$ oc logs eap-app-mongodb-1-r7827
Error from server: Get https://crc-4gdnp-master-0:10250/containerLogs/demo/eap-app-mongodb-1-r7827/eap-app-mongodb: remote error: tls: internal error
```

### PR DESCRIPTION
**Pull request by praveenkumar**
Fixes #218

### CODE REVIEW

File: pkg/crc/machine/machine.go [hunk 1]
```diff
@@ -224,6 +225,14 @@ func Start(startConfig StartConfig) (StartResult, error) {
 		logging.InfoF("Login to the console with user: kubeadmin, password: %s", result.ClusterConfig.KubeAdminPass)
 	}
 
+	// Approve the node certificate.
+	crcOc := oc.GetOC(machineConfig.Name)
```
Comment (gbraad) [inline pkg/crc/machine/machine.go]: just reading this fragment of code makes me wonder what it does:

`get OC for an named instance of CRC` ?... why is `oc` associated with an instance?

File: pkg/crc/oc/oc.go [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+	"github.com/code-ready/crc/pkg/crc/constants"
+	crcos "github.com/code-ready/crc/pkg/os"
+)
+
+type OC struct {
+	OcBinaryPath   string
+	KubeconfigPath string
+}
+
+func GetOC(machineName string) OC {
```
Comment (gbraad) [inline pkg/crc/oc/oc.go]: so, the function name is too ambigious. it should be something like `UseOCWithConfig`, right?

File: pkg/crc/oc/oc.go [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+	oc := OC{
+		OcBinaryPath:   filepath.Join(constants.OcCacheDir, constants.OcBinaryName),
+		KubeconfigPath: filepath.Join(constants.MachineInstanceDir, machineName, "kubeconfig"),
```
Comment (gbraad) [inline pkg/crc/oc/oc.go]: so the `name` is used for the kubeconfig path... this means you do not get oc, but get a configuration.

File: pkg/crc/oc/oc.go [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+	}
+	return oc
+}
+
+func (oc OC) RunOcCommand(args ...string) (string, string, error) {
+	args = append(args, "--kubeconfig", oc.KubeconfigPath)
+	return crcos.RunWithDefaultLocale(oc.OcBinaryPath, args...)
+}
+
+func ApproveCSR(oc OC) error {
```
Comment (gbraad) [inline pkg/crc/oc/oc.go]: `ApproveCSR` for an `OC Config`? ?

Comment (gbraad) [reply pkg/crc/oc/oc.go]: When we talk about `oc` it feels like the command, but here we talk about an `environment` or `configuration`. I would prefer to see that in the naming to avoid this confusion

**Comment by cfergeau** [comment]
Can you explain in the commit log why this is needed, and if this is the right fix long-term, or just a workaround while the root cause is found/fixed?

File: pkg/crc/oc/oc.go (hunk 4 above)
Comment (praveenkumar) [reply pkg/crc/oc/oc.go]: Ah it should be `ApproveNodeCSR` since we are approving the node csr value.

Comment (gbraad) [reply pkg/crc/oc/oc.go]: also... but it is more how `OC` is passed in that sounds merely like a `oc` command wrapper, while it is a configed instance of the `oc` command, right? What aboud `OCConfig`.
