### PR TITLE
Fixes #3298 Changes Windows release preflight message

### LINKED ISSUE #3298: [BUG] Improve check message for Windows 11 users
### General information

  * OS: Windows
  * Hypervisor: Hyper-V
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop 
## CRC version
```bash
CRC version: 2.6.0+e7251680
OpenShift version: 4.10.22
Podman version: 4.1.0
```
  
## CRC status
```bash
DEBU CRC version: 2.6.0+e7251680                                                                                      
DEBU OpenShift version: 4.10.22                                                                                       
DEBU Podman version: 4.1.0                                                                                            
DEBU Running 'crc status'                                                                                             
DEBU Checking file: C:\Users\JeffMAURY\.crc\machines\crc\.crc-exist                                                   
DEBU Checking file: C:\Users\JeffMAURY\.crc\machines\crc\.crc-exist                                                   
DEBU Running 'Hyper-V\Get-VM crc | Select-Object -ExpandProperty State'                                               
CRC VM:          Stopped                                                                                              
OpenShift:       Stopped (v4.10.22)                                                                                   
Podman:                                                                                                               
Disk Usage:      0B of 0B (Inside the CRC VM)                                                                         
Cache Usage:     18.42GB                                                                                              
Cache Directory: C:\Users\JeffMAURY\.crc\cache                                                                        
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId'
DEBU Running '(Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID'                
```

## CRC config
```bash
- consent-telemetry                     : yes
- kubeadmin-password                    : xxxxxx
- memory                                : 16384
- pull-secret-file                      : pull-secret.txt
```

## Host Operating System
```bash

Nom de l'h鍍e:                              DESKTOP-U2EVGBM
Nom du syst確e d'exploitation:              Microsoft Windows 11 Professionnel
Version du syst確e:                         10.0.22000 N/A build 22000
Fabricant du syst確e d'exploitation:        Microsoft Corporation
Configuration du syst確e d'exploitation:    Station de travail autonome
Type de build du syst確e d'exploitation:    Multiprocessor Free
PropriＵaire enregistr・                    Jeff MAURY
Organisation enregistrＦ:                   
Identificateur de produit:                  00330-80819-37372-AA253
Date d'installation originale:              22/07/2022, 09:56:29
Heure de dＮarrage du syst確e:              05/08/2022, 10:43:59
Fabricant du syst確e:                       LENOVO
Mod獲e du syst確e:                          20LAS3NJ0H
Type du syst確e:                            x64-based PC
Processeur(s):                              1 processeur(s) install・s).
                                            [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1910 MHz
Version du BIOS:                            LENOVO N27ET41W (1.27 ), 26/10/2020
RＱertoire Windows:                         C:\WINDOWS
RＱertoire syst確e:                         C:\WINDOWS\system32
PＳiphＳique d'amor㌢ge:                    \Device\HarddiskVolume4
Option rＨionale du syst確e:                fr;Fran㌢is (France)
Param閣res rＨionaux d'entrＦ:              fr;Fran㌢is (France)
Fuseau horaire:                             (UTC+01:00) Bruxelles, Copenhague, Madrid, Paris
MＮoire physique totale:                    32611 Mo
MＮoire physique disponible:                11238 Mo
MＮoire virtuelle: taille maximale:        58211 Mo
MＮoire virtuelle: disponible:             23415 Mo
MＮoire virtuelle: en cours d'utilisation: 34796 Mo
Emplacements des fichiers d'Ｄhange:        C:\pagefile.sys
Domaine:                                    WORKGROUP
Serveur d'ouverture de session:             \\DESKTOP-U2EVGBM
Correctif(s):                               5 Corrections installＦs.
                                            [01]: KB5013889
                                            [02]: KB5007575
                                            [03]: KB5015882
                                            [04]: KB5016353
                                            [05]: KB5015898
Carte(s) rＴeau:                            5 carte(s) rＴeau installＦ(s).
                                            [01]: TAP-Windows Adapter V9
                                                  Nom de la connexion: Ethernet 2
                                                  DHCP activ・:         Oui
                                                  Serveur DHCP:        10.39.207.254
                                                  Adresse(s) IP
                                                  [01]: 10.39.194.86
                                                  [02]: fe80::d527:58a7:4965:c2ad
                                                  [03]: fd10:39:192:1::1255
                                            [02]: Hyper-V Virtual Ethernet Adapter
                                                  Nom de la connexion: vEthernet (minishift)
                                                  DHCP activ・:         Non
                                                  Adresse(s) IP
                                                  [01]: 172.16.0.1
                                                  [02]: fe80::3881:3360:4d27:e878
                                            [03]: Intel(R) Ethernet Connection (4) I219-LM
                                                  Nom de la connexion: Ethernet
                                                  腎at:                Support dＤonnect・
                                            [04]: Intel(R) Dual Band Wireless-AC 8265
                                                  Nom de la connexion: Wi-Fi
                                                  DHCP activ・:         Oui
                                                  Serveur DHCP:        192.168.0.254
                                                  Adresse(s) IP
                                                  [01]: 192.168.0.42
                                            [05]: Bluetooth Device (Personal Area Network)
                                                  Nom de la connexion: Connexion rＴeau Bluetooth
                                                  腎at:                Support dＤonnect・
Configuration requise pour Hyper-V:         Un hyperviseur a Ｕ・dＵect・ Les fonctionnalitＴ nＤessaires ・Hyper-V ne seront pas affichＦs.

```

### Steps to reproduce

  1. `crc start`
  2. 
  3. 
  4. 

### Expected

Check message should not be restricted to Windows 10

### Actual

`INFO Checking Windows 10 release`

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

### PR DESCRIPTION
**Pull request by gbraad**
**Fixes:** Issue #3298 

## Solution/Idea

Removes the specific mention of the Windows 10 as this check also works for Windows 11.

## Testing

1.  run 'setup' on Windows

or

1. run 'start' on Windows

### CODE REVIEW

File: pkg/crc/preflight/preflight_windows.go [hunk 1]
```diff
@@ -25,7 +25,7 @@ var hypervPreflightChecks = []Check{
 	},
 	{
 		configKeySuffix:  "check-windows-version",
-		checkDescription: "Checking Windows 10 release",
+		checkDescription: "Checking Windows release",
```
Comment (praveenkumar) [inline pkg/crc/preflight/preflight_windows.go:28]: 👍🏼

**Review by praveenkumar — APPROVED** [review]
